USE GSSWEB;
GO
 
 --Q1--
 SELECT KEEPER_ID AS KeeperID, USER_CNAME AS CName, USER_ENAME AS EName, YEAR(LEND_DATE) AS BorrowYear
	, COUNT(*) AS BorrowCnt
 FROM dbo.BOOK_LEND_RECORD, dbo.MEMBER_M
 GROUP BY KEEPER_ID, YEAR(LEND_DATE), USER_CNAME, USER_ENAME
 ORDER BY KeeperID, BorrowYear;

 --Q2--
 SELECT TOP 5 BD.BOOK_ID, BOOK_NAME, COUNT(BD.BOOK_ID) AS QTY
 FROM dbo.BOOK_LEND_RECORD AS BLR INNER JOIN dbo.BOOK_DATA AS BD 
	ON BLR.BOOK_ID = BD.BOOK_ID
 GROUP BY BD.BOOK_ID, BOOK_NAME
 ORDER BY QTY DESC;

 --Q3--
 SELECT SPAN_YEAR + '/' + SPAN_START + '~' + SPAN_YEAR + '/' + SPAN_END AS quarter
	,COUNT(MONTH(blr.LEND_DATE)) AS QTY
 FROM dbo.SPAN_TABLE INNER JOIN BOOK_LEND_RECORD AS blr
	ON SPAN_YEAR = YEAR(blr.LEND_DATE)
 WHERE SPAN_YEAR = '2019'
 GROUP BY SPAN_YEAR,SPAN_START,SPAN_END
 ORDER BY Quarter;